version: '3.7'
services:

  db:
    image: postgres
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    networks:
      - mynetwork

  adminer:
    image: adminer
    ports:
      - 8080:8080 
    networks:
      - mynetwork
      
  web:
    build: .
    ports:
      - "5000:80"
    depends_on:
      - db
    environment:
      CONNECTION_STRING: Server=localhost;Port=5432;Database=mydb;Username=myuser;Password=mypassword
    volumes:
      - .:/app
    networks:
      - mynetwork

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - web
    environment:
      REACT_APP_API_URL: http://web:80/api
    volumes:
      - ./client:/app
    networks:
      - mynetwork

networks:
  mynetwork: