version: '3.7'
services:

  db:
    image: postgres
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - mynetwork
      
  web:
    build: .
    ports:
      - "5000:80"
    depends_on:
      - db
    volumes:
      - .:/app
    networks:
      - mynetwork

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - web
    volumes:
      - ./client:/app
    networks:
      - mynetwork

volumes:
  pgdata:

networks:
  mynetwork: